GET http://localhost:3000/guildmates/

###

POST http://localhost:3000/guildmates
Content-Type: application/json

{
    "name": "tiroxxx",
    "startingGP": "5000000",
    "twDefense": "300",
    "twOffense": "40"
}

###

DELETE http://localhost:3000/guildmates/6083222177c2203060e5cf49

###

PATCH http://localhost:3000/guildmates/6083268bd9f923116cafdd97
Content-Type: application/json

{
    "name": "chris"
}

###

GET http://swgoh.gg/api/player/736951577